### ISSUE TITLE
SearchApi usage example

### ISSUE THREAD

**Issue by antonu17** [TheJumpCloud/jcapi-go#17]
Hi guys.
Can you please provide a working example of using SearchApi, specifically SearchSystemusersPost?
When I tried to use it like

	optionals := map[string]interface{}{
		"body": jcApi1.Search{
			Filter: "[\"email\": \"" + email + "\"]",
		},
	}
	users, _, err := jcAPIv1.SearchApi.SearchSystemusersPost(ctx, contentType, accept, optionals)

It produces this request body:
```
{"filter":"[\"email\": \"test@example.org\"]"}
```

but I expect:
```
{"filter": [{"email" : "test@example.org"}]}
```

Probably I'm using it wrong. :raised_hands:

**Comment by jpvajda** [comment]
@antonu17 let me take a look for you....

**Comment by antonu17** [comment]
Hi again.
I see the problem is in the Search struct. I has Filter field of type string, so the whole value of this field is always quoted. So, I decided ok fine, using `SearchApi` is not the only option I can use for my case - find user ID for given email. I decided to switch on using `SystemusersApi` and use `SystemusersList()` with filter `"filter": fmt.Sprintf("email:eq:%s", email)`, and this time API call succeeded!
BUT, guess what? User's ID renders empty string. This time there is a problem with `Systemuserreturn` structure. It can't read user's ID, because of Id field tag is wrong:
```
Id string `json:"id,omitempty"`    but should be     Id string `json:"_id,omitempty"`
```

**Comment by jpvajda** [comment]
@antonu17 I see. This should be fixed in the upcoming Sept release of the SDK. I assume it relates to this issue found by a Developer in our Python SDK:  https://github.com/TheJumpCloud/jcapi-python/pull/15. I've corrected this our API Docs and YAML so once the SDKs get release it should likely be resolved.

**Comment by antonu17** [comment]
In addition `Systemuserreturn` structure has a field 

    SshKeys []string `json:"ssh_keys,omitempty"`

but in `/api/systemusers` payload it looks:

      "ssh_keys": [
        {
          "create_date": "2018-01-01T11:57:20.953Z",
          "_id": "7cba756ca7b6cac67c7",
          "public_key": "ssh-rsa .....",
          "name": "my_key"
        }
      ]

A valid ssh_key item struct is required

**Comment by jpvajda** [comment]
@antonu17 Thanks for the feedback it looks like we aren't referencing the new `ssh key` models from those `system user` models. I can fix that in our documentation which then can be pushed to the SDKs.

**Comment by jpvajda** [comment]
@antonu17 the `address`` phone` issue I'm also looking into.

**Comment by jpvajda** [comment]
@antonu17  how does this look for the SSH key issue you reported?  https://docs.jumpcloud.com/1.0/systemusers/list-a-system-user

**Comment by antonu17** [comment]
@jpvajda it looks correct. Hope this will generate right Go code.
